version: '3.9'

services:
  yugabyted-0:
    container_name: yugabyted-0
    hostname: yugabyted-0
    image: yugabytedb/yugabyte:2.23.0.0-b710
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --secure --daemon=false --advertise_address=yugabyted-0 --tserver_flags='ysql_enable_profile=true' --ysql_enable_auth=true
    restart: unless-stopped
    ports:
      - "7000:7000"
      - "7100:7100"
      - "9000:9000"
      - "5433:5433"
      - "15433:15433"
    healthcheck:
      test: ["CMD", "/home/yugabyte/postgres/bin/pg_isready", "-h", "yugabyted-0"]
      interval: 10s
      timeout: 5s
      retries: 10
